### ISSUE TITLE
Nginx Documentation Not Accounting For New Users Permissions

### ISSUE THREAD

**Issue by ayezee33** [raspberrypi/documentation#428] opened 2016-09-17 00:31 UTC
Hello when I go to cd /usr/share/nginx/www/ and change the content of the file I am told I don't have permissions to change the file. 

However, if I go to /var/www/html and make a change not only can I save it but it shows on my localhost location. 

Is the documentation wrong or am I missing something? What is the difference between these two locations?

Here is the documentation I am following https://www.raspberrypi.org/documentation/remote-access/web-server/nginx.md

**Comment by Ruffio** [comment] 2017-01-07 21:18
Xref.: https://github.com/raspberrypi/documentation/issues/370

**Comment by JamesH65** [comment] 2017-03-02 17:00
Duplicate of  #370 which has a PR going through. Closing.

**Closed by JamesH65** 2017-03-02 17:00 UTC
