### ISSUE TITLE
We are still waiting for Boot EEPROM hardware write protection information

### ISSUE THREAD

**Issue by McuMirror** [raspberrypi/documentation#1464] opened 2020-04-11 12:44 UTC
".. it is possible to physically write-protect both EEPROMs via a simple resistor change on the board. Details will be published in the schematics." -- Documentation

Not yet indicated in the schematics. Please add this information.
We'll have to wait for the Raspberry Pi org to release the EEPROM part of the schematics or simply tell us which trace/resistor to cut/remove. 

sorry for the new issue but i think this subject is forgotten.

**Comment by JamesH65** [comment] 2020-04-11 12:59
@jimbojr @mike-stimson Is this your domain?

**Comment by lurch** [comment] 2020-04-14 10:52
Closing as a duplicate of #1302

**Closed by lurch** 2020-04-14 10:52 UTC

**Comment by McuMirror** [comment] 2020-04-14 13:07
OK. Close this issue, but a simple explanation should not take weeks/months.

**Comment by JamesH65** [comment] 2020-04-14 13:17
Please use the linked issue for any comments, this one is closed.
