### ISSUE TITLE
Update power supply section

### ISSUE THREAD

**Issue by LizUpton** [raspberrypi/documentation#3490] opened 2024-01-19 18:38 UTC
https://github.com/raspberrypi/documentation/edit/develop/documentation/asciidoc/computers/raspberry-pi/power-supplies.adoc

No Pi 5 material here at all (I've mentioned this in the Pi 5 page issue); and as I've gone through this with my little red pen it became clear that a lot of these tests were last run in 2016; we could probably do with going through the numbers again. Sorry Nate; thank you!

**Comment by aallan** [comment] 2024-01-19 18:46
Duplicate of #3227.

**Closed by aallan** 2024-01-19 18:46 UTC
Labels: duplicate, pi5 5️⃣, update
