### ISSUE TITLE
Missing dimensions for official PI3B+ case "lid"

### ISSUE THREAD

**Issue by crazyimp** [raspberrypi/documentation#1347] opened 2019-11-26 20:30 UTC
Please provide more information or 3D model (.stl files for example) regarding the top lid of the official PI3B+ case (https://www.raspberrypi.org/products/raspberry-pi-3-case/). Optionally, the walls on the long edge of the case, as they are also removable.
The dimension for the case can be found here: https://www.raspberrypi.org/documentation/hardware/raspberrypi/mechanical/rpi_MECH_3bplus_case.pdf which is linked here: https://www.raspberrypi.org/documentation/hardware/raspberrypi/mechanical/README.md .
The drawing doesn't include the dimensions for the mentioned sub-parts.

Motivation for this: allowing modifications to the case by printing new sides and lids with additional openings and maybe mounted extra buttons without destroying parts of the case :).

**Comment by JamesH65** [comment] 2019-11-27 11:14
@jimbojr @ghollingworth Are we likely to be able to supply this information?

**Comment by lurch** [comment] 2019-12-02 10:09
On a side-note, I've just noticed that https://www.raspberrypi.org/documentation/hardware/raspberrypi/mechanical/README.md doesn't have anything about the Pi 4B case either.

**Comment by andrum99** [comment] 2019-12-02 17:39
> Motivation for this: allowing modifications to the case by printing new sides and lids with additional openings and maybe mounted extra buttons without destroying parts of the case :).

For your use case, measuring the case with calipers should be sufficient, since 3D printed objects are not massively accurate and will often need a bit of sanding etc to make fit anyway.

**Comment by crazyimp** [comment] 2019-12-05 11:26
> > Motivation for this: allowing modifications to the case by printing new sides and lids with additional openings and maybe mounted extra buttons without destroying parts of the case :).
> 
> For your use case, measuring the case with calipers should be sufficient, since 3D printed objects are not massively accurate and will often need a bit of sanding etc to make fit anyway.

Due to all the curves on the requested parts, it's quite annoying to measure. "Adding" tolerances (removing material before printing) to the model is easy on the other hand.

**Comment by JamesH65** [comment] 2020-01-02 16:41
@jimbojr @ghollingworth @Roger-Thornton Are we likely to be able to supply this information?

**Comment by ghollingworth** [comment] 2020-01-02 16:53
No, we've looked into it and we've decided that we're not going to be able to provide this information.

**Comment by JamesH65** [comment] 2020-01-03 10:23
Sorry, closing as a Won't Fix. This means that although the issue is acknowledged, it is felt that no further action is likely. This may be down to a bad benefit vs cost analysis, or it may actually not be possible to fix.

**Closed by JamesH65** 2020-01-03 10:23 UTC
