### ISSUE TITLE
/boot/config.txt rotate screen & mouse

### ISSUE THREAD

**Issue by greedyvegan** [raspberrypi/documentation#3559] opened 2024-03-15 21:55 UTC
Raspberry 4 running Debian GNU/Linux 12 (bookworm)

the directions to rotate the screen says to go to /boot/config.txt
the config.txt in boot says to go to /boot/firmware/config.txt

wlr-randr --output HDMI-A-1 --transform 90
xrandr --output HDMI-1 --rotate right
DISPLAY=:0 wlr-randr --output HDMI-1 --rotate right
xrandr --output HDMI-1 --reflect x

doesn't work, anymore

error: XDG_RUNTIME_DIR is invalid or not set in the environment.
failed to connect to display
are my results

when I rotate the screen from the pi, only the screen rotates; the cursor/mouse does not.
Left is up, up is right etc.

**Comment by aallan** [comment] 2024-03-17 17:58
Duplicate of #3353

**Closed by aallan** 2024-03-17 17:58 UTC
Labels: duplicate
