### ISSUE TITLE
setting up an apache web server - PHP instructions incorrect?

### ISSUE THREAD

**Issue by windy54** [raspberrypi/documentation#71] opened 2014-06-03 12:08 UTC
I have just worked through this example and could not get the PHP to work.

The instructions say to enter
<?php echo "hello world"

I had to enter <?php echo "hello world" ?>

I believe the ; on the 3 examples needs to be replaced by ?>

As a newcomer to php I would like to see the complete index.php file, when it did not work I was not sure whether I had put it in the wrong place, in the body not the heaer etc.

**Comment by lurch** [comment] 2015-03-02 12:08
The issues that this is listed as a duplicate of (#65 and #160) have been closed by 6e83bd1, so presumably this should have been closed too.

**Closed by lurch** 2015-03-02 12:08 UTC
Labels: duplicate, invalid
