### ISSUE TITLE
Alternate method to put image on SD card for mac osx - apple-pi-baker

### ISSUE THREAD

**Issue by dliloch** [raspberrypi/documentation#320] opened 2016-03-02 13:15 UTC
I found this to be extremely simple .. especially compared to the current instructions for the mac.
http://www.tweaking4all.com/hardware/raspberry-pi/macosx-apple-pi-baker/
You might want to put this in as an alternative. It has an initialization button to format the card then it transfers the image from .img or directly off the .zip!

**Comment by lurch** [comment] 2016-03-02 14:37
Duplicate of #315 ?

**Comment by dliloch** [comment] 2016-03-02 17:23
Yes..sorry..I did not do a through enough search..

**Closed** 2016-03-02 19:04 UTC
Labels: macosx
