### ISSUE TITLE
Zero mechanical drawing not up to date

### ISSUE THREAD

**Issue by ghent360** [raspberrypi/documentation#382] opened 2016-06-26 20:29 UTC
Can you add the mechanical drawing for the Zero v1.3?

**Comment by maurbeck** [comment] 2016-07-10 16:04
I second this! v1.3 with the camera connector specs would be appreciated to help building cases that account for the camera cable, etc.

**Comment by JamesH65** [comment] 2017-03-02 16:37
I'll see what I can do to get this sorted. No timescales!

**Comment by JamesH65** [comment] 2017-03-06 12:00
@Roger-Thornton Also see #188, #95

**Comment by JamesH65** [comment] 2017-03-09 16:04
closing - please see linked issue #188

**Comment by lurch** [comment] 2018-02-04 12:40
Should this be re-opened? It was closed as a duplicate of #188 , and #642 claimed to close #188 , but #642 didn't add the PiZero 1.3 mechanical drawing that was being asked for here?

**Comment by JamesH65** [comment] 2018-02-05 10:49
Ah yes, we do plan on releasing it, but it won;t be right now - very busy.

**Comment by JamesH65** [comment] 2018-07-02 16:01
@Roger-Thornton This drawing too....!

**Comment by JamesH65** [comment] 2018-09-12 15:06
@Roger-Thornton Did we get anywhere with updating the mechanical drawings for the latest releases? https://www.raspberrypi.org/documentation/hardware/raspberrypi/mechanical/README.md seems to be missing the Zero 1.3, W and WH, Pi2 and the somewhat older but still sold A+.

**Comment by JamesH65** [comment] 2019-02-07 14:02
@Roger-Thornton Are there any plans to update/release any of these missing mech drawings?

**Comment by JamesH65** [comment] 2019-02-07 15:16
OK, just uploaded the Zero 1.3 files top github, should appear on website within an hour. We have no plans to add any for the Pi2 due to its age, so closing this ticket.

**Closed by JamesH65** 2019-02-07 15:16 UTC
