### ISSUE TITLE
CAD files (3d) for designing 3D printing, parts, etc

### ISSUE THREAD

**Issue by jgwinner** [raspberrypi/documentation#1059] opened 2019-01-08 20:44 UTC
Hello:

My understanding from a few files on Thingiverse, is that there were some design files for the various Raspberry Pi physical boards.

I guess manufacturers could have some components slightly different in size than others, but I think more than a DXF diagram, a reference implementation / official guidelines for things like volume, intrusions, etc. would be really handy; preferably on the mechanical drawings page.

Forgive me if this information is posted somewhere else; I just checked and only saw PDF and DXF file formats.

For people making cases, the "attribution" requirements on a mostly non-commercial site like Thingiverse may be a problem too, making an official 3D file (Blender, OBJ, GLTF, or other open format) a really great thing.

Thank you for listening,

== John ==

**Comment by JamesH65** [comment] 2019-01-10 10:08
Will ask around, but I don't believe we have anything like that at all, and it seems unlikely we would generate them given our workload. Sorry.

**Comment by lurch** [comment] 2019-01-10 11:15
See also #95

**Comment by JamesH65** [comment] 2019-02-07 13:49
I cannot see us doing this in the near or even medium term. So closing as a Won't Fix. This means that although the issue is acknowledged, it is felt that no further action is likely.

**Closed by JamesH65** 2019-02-07 13:49 UTC
Labels: enhancement

**Comment by jgwinner** [comment] 2019-02-07 14:15
Darn. Thanks for your consideration.

Some CAD files do it automatically, was hoping it was just an export, but I understand on the workload issue. There are some versions on the web but some are pretty sketchy. For reference, if others stumble on this issue:

https://3dwarehouse.sketchup.com/model/f18fc33e-3c42-433f-aa51-021c22689148/Raspberry-PI-model-B

https://grabcad.com/library/raspberry-pi-model-b-2

I do not know how accurate these are.

        == John ==

**Comment by JamesH65** [comment] 2019-02-07 14:59
We don't have CAD files for the boards, they are done on PCB design tools, not CAD systems, so there is no export possible AFAIK.

**Comment by jgwinner** [comment] 2019-02-07 15:18
It depends on what tool. I know AutoTRAX DEX does it. I think a few others do too, it's been a while since I've used PCB software, frankly.

        == John ==
