### ISSUE TITLE
Hardware documentation for the BCM2837 in rPi 3

### ISSUE THREAD

**Issue by machinaut** [raspberrypi/documentation#473] opened 2016-12-16 04:13 UTC
The hardware documentation seems to only cover the 1 and 2 chips (BCM 2835 and 2836 respectively).

**Comment by machinaut** [comment] 2016-12-16 04:19
Found this: https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/bootmodes/sdcard.md

Is it a matter of reading a datasheet and translating it into a human-friendly doc?

**Comment by bennuttall** [comment] 2016-12-16 11:14
Duplicate of #337

**Closed by bennuttall** 2016-12-16 11:14 UTC
