### ISSUE TITLE
Use adduser instead of useradd in "Securing your Raspberry Pi"

### ISSUE THREAD

**Issue by Benestar** [raspberrypi/documentation#824] opened 2018-02-15 16:19 UTC
When using `useradd` all the default options are apparently ignored. [1] This especially leads to the wrong shell being selected and also some other defaults missing. Therefore, it should rather be suggested to use the `adduser` command which does not have these problems. See also [2] for more information.

[1] From `man useradd`: "useradd is a low level utility for adding users. On Debian, administrators should usually use adduser(8) instead."
[2] https://unix.stackexchange.com/a/321235

**Comment by JamesH65** [comment] 2018-02-19 10:28
Woudl you be up for doing a PR to update the page? Seems like a good idea to me.

**Comment by JamesH65** [comment] 2018-02-19 10:57
Ah, just seen this is a duplicate of https://github.com/raspberrypi/documentation/issues/779

I'll close this and can be dealt with on other issue.

**Closed by JamesH65** 2018-02-19 10:57 UTC
Labels: Pull request invited from originator
