### ISSUE TITLE
SD Card for Raspberry Pi

### ISSUE THREAD

**Issue by juanca1944** [raspberrypi/documentation#2325] opened 2021-12-21 23:40 UTC
"Because of a hardware limitation in the Raspberry Pi Zero, 1 and 2, the boot partition on the SD card must be 256GB or less..."

I think it must say 256MB not 256GB

**Comment by Lanwalker** [comment] 2021-12-21 23:47
I doubt that 256 ' MB '. It sure isn't on the Pi 4

Robert Gamble - Disabled IT Analyst/Communication Systems Engineer & Automation Test, Control and Design Systems Engineer, 82nd Airborne Artillery ( 1977 ), National Admin for the United States Minutemen - American Patriots Coalition, Service Officer for the Newton American Legion, East Fultonham, Ohio

***@***.*** ( preferred )
***@***.***
***@***.***
***@***.***







On Tuesday, December 21, 2021, 06:40:21 PM EST, JuanCarlos Fischer ***@***.***> wrote: 







"Because of a hardware limitation in the Raspberry Pi Zero, 1 and 2, the boot partition on the SD card must be 256GB or less..."

I think it must say 256MB not 256GB

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lurch** [comment] 2021-12-22 01:08
Duplicate of #2263 ?

**Comment by juanca1944** [comment] 2021-12-22 13:46
Yes Lurch you are right, it is a duplicate. Sorry.
We are talking about a microSD card not a HDD. As an example I use a 2GB microSD with  DietPi and a boot partition of 128MB. 
If you use or used a Raspberry PI you must noticed that all the boot partitions are 256MB or less, even Windows, of course there must be an exception.

**Closed** 2021-12-22 18:22 UTC
Labels: duplicate, invalid
