### ISSUE TITLE
Camera connector pinout is reversed in CM3 IO board

### ISSUE THREAD

**Issue by ebenolson** [raspberrypi/documentation#1081] opened 2019-02-07 20:39 UTC
In this image, you can see that on the camera adapter board, the differential pairs are on the left side of the connector (facing into the connector). However, on the IO board, the differential pairs have swapped to the right side.

This is necessary of course for the signals to match up, however it means the numbering of the connector needs to be reversed in the schematic.

![image](https://user-images.githubusercontent.com/544718/52441185-0a020b80-2aee-11e9-9349-01a607018694.png)

**Comment by lurch** [comment] 2019-02-08 10:34
Is this a duplicate of #847 ?

**Comment by ebenolson** [comment] 2019-02-08 11:27
Looks like it! Same thing happened to me, guess I'll close this and add my
vote there.

**Comment by ebenolson** [comment] 2019-02-08 11:50
Actually, reopening as it's not really a duplicate - same mistake, but affects a different board and schematic file.

**Comment by JamesH65** [comment] 2020-11-19 11:20
@jimbojr Was this schematics issue fixed?

**Closed** 2021-06-17 10:59 UTC
Labels: idle
